/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		ChannelSidebar: typeof import('./components/common/ChannelSidebar.vue')['default'];
		ElAside: typeof import('element-plus/es')['ElAside'];
		ElCol: typeof import('element-plus/es')['ElCol'];
		ElContainer: typeof import('element-plus/es')['ElContainer'];
		ElFooter: typeof import('element-plus/es')['ElFooter'];
		ElHeader: typeof import('element-plus/es')['ElHeader'];
		ElMain: typeof import('element-plus/es')['ElMain'];
		ElMenu: typeof import('element-plus/es')['ElMenu'];
		ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
		ElRow: typeof import('element-plus/es')['ElRow'];
		NotFound: typeof import('./components/NotFound.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
	}
}
